### ISSUE TITLE
[Bug]: Recent Finder Files not working

### ISSUE THREAD

**Issue by mjknght** [chrisgrieser/alfred-quick-file-access#1]
### Checklist

- [X] I have updated to the [latest version of this workflow](./releases/latest).
- [X] I am using Alfred 5 or later.

### Alfred version

5.5.1 (2273)

### macOS version

Sonoma 14.6.1

### Bug Description

Results never appear when using the `rec` command.

### To Reproduce

When I run the `rec` command, the debugger shows the below and no results appear. (I have installed ripgrep using the specified command.) Thanks in advance for any help you can offer – it's a great idea for a workflow! 🙂

### Debugging Log

```Text
[16:36:57.370] Quick File Access[Script Filter] Queuing argument '(null)'
```

### Workflow Configuration

<img width="516" alt="Screenshot 2024-10-04 at 4 38 18 PM" src="https://github.com/user-attachments/assets/c84b2ca3-9632-4e62-ac29-af6454969eba">

**Comment by chrisgrieser** [comment]
Do you have ripgrep installed?

**Comment by chrisgrieser** [comment]
Just in case, I added some logging and a potential fix for an edge case I found, so you might try version 1.0.3 and run the command again:

https://github.com/chrisgrieser/alfred-quick-file-access/releases/download/1.0.3/alfred-quick-file-access.alfredworkflow

**Comment by mjknght** [comment]
Hi Chris! Thanks for a quick response. I've updated to 1.0.3, and find I still have the same problem. When I run `which -a rg` I get:

```
mark@Marks-Laptop ~ %  which -a rg
/opt/homebrew/bin/rg
```

**Comment by chrisgrieser** [comment]
I added some logging to 1.0.3, so please run the command again and copy the debugging log again, which should now include some more information

**Comment by mjknght** [comment]
Hi! Afraid the debugger appears to output the same way with 1.0.3 (checked plist to confirm I was on this version):

`[17:04:47.132] Quick File Access[Script Filter] Queuing argument '(null)'`

**Comment by mjknght** [comment]
Front Finder window, download folder and trash work. Recent files and also tag don’t work – but then again, I haven’t set up a tag. Thanks again.

**Comment by chrisgrieser** [comment]
tbh, I do not have any idea why this does not work for you then. `Queuing argument '(null)'` as output should not be possible, it should either throw an error or a log message.

**Comment by mjknght** [comment]
Hmm, OK, thanks for looking into it! I’m no developer, but will let you know what the issue is if do happen to figure out what’s up on my side…

**Comment by mjknght** [comment]
Hi Chris,

I feel a little silly – I happened to notice that it *is* working after all; it's just very slow. Perhaps the number of recently modified files?

```
[12:03:08.699] Quick File Access[Script Filter] Queuing argument '(null)'
[12:03:33.868] Quick File Access[Script Filter] Script with argv '(null)' finished
[12:03:33.873] STDERR: Quick File Access[Script Filter] KEYWORD: rec
SHELL COMMAND
export PATH=/usr/local/lib:/usr/local/bin:/opt/homebrew/bin/:$PATH ; cd "/Users/mark" && rg --no-config --files --binary --sortr=modified --ignore-file="/Users/mark/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.6B8455D0-F4C7-426C-95D0-FCC9942990B3/scripts/home-icloud-ignore-file"
```

**Comment by chrisgrieser** [comment]
Aha!

Yes, the number of files could be an issue. You could try to lower the value in the settings, but if you have a large home directory, it might be slow regardless. 

How large of a home directory do you have?

**Comment by mjknght** [comment]
Large, it seems! 20GB or so. I will try to exclude a few folders to see if that speeds things up… Thanks!

**Comment by gaufde** [comment]
@chrisgrieser Do you have any performance tips? My home folder is apparently ~550GB, with the majority of that space going to Pictures and Movies (Though my library folder is about 100GB). The `rec` keyword takes ~11 seconds for me.

**Comment by chrisgrieser** [comment]
It's not that much the size of the folder, but rather the number of files in them. If you have many, many files in there, there is unfortunately little this workflow can do. 

One thing you might consider is arching (compressing as zip) directories you don't actively use. This not only reduces file size, but also the number of files, and as a side-benefit, can also speed up other things (backup operations, Spotlight/Alfred in general.)
